### PR TITLE
Free mobile layout hopefully

### PR DESCRIPTION
**Pull request by adueppen**

### CODE REVIEW

**Comment by fennifith** [comment]
Aught

**Comment by fennifith** [comment]
Dammit spellchecker

**Comment by fennifith** [comment]
Well nvm I'll just murge

**Comment by fennifith** [comment]
...I hate myself

**Comment by adueppen** [comment]
...you know there's an edit button right James?

**Comment by fennifith** [comment]
@adueppen there isn't one on mobile, and I was too lazy to go into the menu to check the 'show desktop version' option last night.

**Pull request merged**
